GET https://prisma-supabase-vercel.vercel.app/users HTTP/1.1
content-type: application/json

###
GET https://prisma-supabase-vercel.vercel.app/users/1 HTTP/1.1
content-type: application/json

###
POST https://prisma-supabase-vercel.vercel.app/users HTTP/1.1
content-type: application/json

{
    
    "created_at": "2024-12-28T07:53:41.300Z",
    "username": "admin1",
    "password": "admin",
    "email": "admin1@finitecode.in"
}

###
PUT https://prisma-supabase-vercel.vercel.app/users/1 HTTP/1.1
content-type: application/json

{
    
    "created_at": "2024-12-28T07:53:41.300Z",
    "username": "admin",
    "password": "adminadminadmin",
    "email": "admin@finitecode.in"
}

###
DELETE https://prisma-supabase-vercel.vercel.app/users/1 HTTP/1.1
content-type: application/json
